#!/bin/bash

g++ -std=c++11 -m64 -fpic -c redelClient.cpp graphCreator.cpp backups.cpp
g++ -shared redelClient.o graphCreator.o backups.o -o libRedelClient.so

g++ -std=c++11  -m64 -fpic -c redelServer.cpp graphCreator.cpp backups.cpp
g++ -shared redelServer.o graphCreator.o backups.o -o libRedelServer.so
