#!/bin/bash

g++ -std=c++11 -m64 -O3 -fpic -c redelClient.cpp graphCreator.cpp backups.cpp
g++ -shared redelClient.o graphCreator.o backups.o -o ../client/libRedelClient.so

rm redelClient.o graphCreator.o backups.o
